language: ruby
sudo: false
addons:
  apt:
    packages:
    - update
    - zlib1g-dev
    - libncurses5-dev
    - libtinfo-dev   
before_script:
  - cd ext
  - ruby mkrf_conf.rb
  - rake -f Rakefile
  - cd ../
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.2.3
