language: ruby
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
    - libtinfo-dev   
before_script:
  - cd ext
  - ruby mkrf_conf.rb
  - rake -f Rakefile
  - cd ../
rvm:
  - 2.0.9
  - 2.1.10
  - 2.2.2
  - 2.2.3
  - 2.2.5
  - 2.3.1
